import streamlit as st
import pandas as pd
import numpy as np
from PIL import Image

st.title("""Customized Discount Prediction Application""")
image2 = Image.open('./Maverick.jpeg')
st.sidebar.image(image2,use_column_width=True)

st.header("Please enter the following inputs")

def user_input_features():
    Ship_to_ID = st.number_input('Please enter the Ship-to ID',value=int())
    Volume_2019 = st.number_input('Please enter the Volume 2019',format='%f',value=float())
    Volume_2018 = st.number_input('Please enter the Volume 2018',format='%f',value=float())
    sfdc_tier = st.selectbox('Please select the sfdc_tier',('Tier 1', 'Tier 2', 'Tier 0'))
    poc_image = st.selectbox('Please select the poc_image',('Mainstream', 'Premium'))
    segment = st.selectbox('Please select the segment',('Entertainment Led', 'Drink Led', 'Institutional', 'Food Led','Wholesaler'))
    sub_segment = st.selectbox('Please select sub_segment',('Events', 'Party Place', 'Institutional', 'Bar', 'Restaurant','Sports Venue', 'Recreational', 'Beer bar', 'Hybrid','Quick Dining', 'Music Venue', 'Cocktail Bar', 'Wholesaler','Local Bar', 'Sub Agent'))
    Product_Set = st.selectbox('Please select the Product Set',('RETURNABLE_BOTTLE_JUPILER_JUPILER PILS',
       'RETURNABLE_BOTTLE_PIEDBOEUF_PIEDBOEUF TRIPLE',
       'OW_BULK_JUPILER_JUPILER PILS',
       'RETURNABLE_KEG_JUPILER_JUPILER PILS',
       'RETURNABLE_BOTTLE_JUPILER_JUPILER 0,0',
       'RETURNABLE_BOTTLE_PIEDBOEUF_PIEDBOEUF BLONDE',
       'RETURNABLE_BOTTLE_PIEDBOEUF_PIEDBOEUF FONCEE',
       'RETURNABLE_KEG_DIEKIRCH_DIEKIRCH PILS',
       'RETURNABLE_BOTTLE_BELLE VUE_BELLE VUE EXTRA KRIEK',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN ROSEE',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN WHITE',
       'RETURNABLE_BOTTLE_LEFFE_FLAVOURED ALCOHOLIC',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE BLONDE',
       'RETURNABLE_BOTTLE_TRIPEL KARMELIET_TRIPEL KARMELIET',
       'RETURNABLE_KEG_BELLE VUE_BELLE VUE EXTRA KRIEK',
       'RETURNABLE_KEG_HOEGAARDEN_HOEGAARDEN ROSEE',
       'RETURNABLE_KEG_HOEGAARDEN_HOEGAARDEN WHITE',
       'RETURNABLE_KEG_LEFFE_LEFFE BLONDE', 'OW_CAN_JUPILER_JUPILER PILS',
       'OW_BOTTLE_GOOSE ISLAND_GOOSE ISLAND IPA',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN ROSE 0,0',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE BRUNE',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE SANS ALCOOL/ALCOHOLVRIJ',
       'RETURNABLE_BOTTLE_BELLE VUE_BELLE VUE GUEUZE',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE RUBY',
       'RETURNABLE_BOTTLE_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'RETURNABLE_BOTTLE_BELLE VUE_BELLE VUE KRIEK CLASSIQUE',
       'OW_CAN_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'RETURNABLE_KEG_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'OW_CAN_JUPILER_JUPILER 0,0', 'RETURNABLE_KEG_LEFFE_LEFFE BRUNE',
       'OW_BOTTLE_CORONA_CORONA EXTRA',
       'RETURNABLE_KEG_TRIPEL KARMELIET_TRIPEL KARMELIET',
       'RETURNABLE_KEG_JUPILER_JUPILER BLUE',
       'RETURNABLE_BOTTLE_VIEUX TEMPS_VIEUX TEMPS REGULAR',
       'RETURNABLE_KEG_LEFFE_FLAVOURED ALCOHOLIC',
       'RETURNABLE_BOTTLE_JUPILER_JUPILER BLUE',
       'RETURNABLE_KEG_SCOTCH CTS_SCOTCH CTS',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEG RADLER LEMON 0,0',
       'RETURNABLE_BOTTLE_PURE BLONDE_PURE BLONDE REGULAR',
       'OW_BOTTLE_CUBANISTO_CUBANISTO RUM',
       'OW_BOTTLE_GINETTE_ GINETTE LAGER',
       'OW_BOTTLE_GINETTE_GINETTE BLANCHE',
       'OW_BOTTLE_GINETTE_GINETTE FRUIT',
       'OW_BOTTLE_GINETTE_GINETTE TRIPEL',
       'RETURNABLE_KEG_GINETTE_ GINETTE LAGER',
       'RETURNABLE_KEG_GOOSE ISLAND_GOOSE ISLAND IPA',
       'RETURNABLE_KEG_KWAK_KWAK',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN JULIUS',
       'RETURNABLE_BOTTLE_KWAK_KWAK', 'RETURNABLE_BOTTLE_LEFFE_LEFFE',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE ROYALE',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE TRIPLE',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE BLONDE',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE BRUNE',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN BEATRIX',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN YELLOW',
       'RETURNABLE_BOTTLE_SCOTCH CTS_SCOTCH CTS',
       'RETURNABLE_KEG_PURE BLONDE_PURE BLONDE REGULAR',
       'RETURNABLE_BOTTLE_BASS_BASS PALE ALE',
       'RETURNABLE_BOTTLE_KRUGER_KRUGER EXPORT',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN 0,0',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE RITUEL 9░',
       'RETURNABLE_PERFECTDRAFT_HOEGAARDEN_HOEGAARDEN WHITE',
       'RETURNABLE_PERFECTDRAFT_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN GRAND CRU',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE ROYALE CASCADE IPA',
       'OW_BOTTLE_LEFFE_LEFFE BLONDE',
       'OW_BOTTLE_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'OW_BOTTLE_GINETTE_GINETTE BLONDE',
       'OW_CAN_LEFFE_LEFFE SANS ALCOOL/ALCOHOLVRIJ',
       'RETURNABLE_BOTTLE_HOEGAARDEN_HOEGAARDEN FORBIDDEN FRUIT',
       'RETURNABLE_KEG_LEFFE_LEFFE ROYALE CASCADE IPA',
       'RETURNABLE_KEG_LEFFE_LEFFE RUBY',
       'OW_CAN_HOEGAARDEN_ HOEGAARDEN RADLER AGRUM 0,0',
       'OW_CAN_HOEGAARDEN_HOEGAARDEN ROSE 0,0',
       "RETURNABLE_BOTTLE_BECK'S_BECK'S REGULAR",
       'RETURNABLE_BOTTLE_HORSE ALE_HORSE ALE',
       'RETURNABLE_KEG_HOEGAARDEN_HOEGAARDEN JULIUS',
       'RETURNABLE_KEG_LEFFE_LEFFE', 'OW_CAN_HOEGAARDEN_HOEGAARDEN WHITE',
       'OW_CAN_LEFFE_LEFFE BLONDE',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE RADIEUSE',
       'RETURNABLE_PERFECTDRAFT_JUPILER_JUPILER PILS',
       'RETURNABLE_PERFECTDRAFT_LEFFE_FLAVOURED ALCOHOLIC',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE ROYALE',
       'OW_BOTTLE_LEFFE_LEFFE RUBY',
       'RETURNABLE_KEG_CUBANISTO_CUBANISTO RUM',
       'OW_CAN_HOEGAARDEN_HOEGAARDEN 0,0',
       'RETURNABLE_KEG_HOEGAARDEN_HOEGAARDEN GRAND CRU',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE RUBY',
       'OW_CAN_HOEGAARDEN_HOEGAARDEN ROSEE', 'OW_CAN_LEFFE_LEFFE BRUNE',
       'RETURNABLE_KEG_DIEKIRCH_DIEKIRCH XMAS BEER',
       'OW_CAN_CUBANISTO_CUBANISTO RUM', 'OW_CAN_JUPILER_JUPILER BLUE',
       'OW_CAN_PURE BLONDE_PURE BLONDE REGULAR',
       'RETURNABLE_KEG_JUPILER_JUPILER 0,0',
       'RETURNABLE_PERFECTDRAFT_HOEGAARDEN_HOEGAARDEN ROSEE',
       'OW_CAN_BELLE VUE_BELLE VUE EXTRA KRIEK',
       'RETURNABLE_BOTTLE_GINDER-ALE_GINDER-ALE',
       'RETURNABLE_BOTTLE_LEFFE_LEFF NECT',
       'OW_CAN_HOEGAARDEN_HOEG RADLER LEMON 0,0',
       'RETURNABLE_BOTTLE_DIEKIRCH_DIEKIRCH GRAND CRU',
       'OW_BOTTLE_DEUS_DEUS',
       'OW_BULK_STELLA ARTOIS_STELLA ARTOIS REGULAR',
       'RETURNABLE_BOTTLE_SAFIR_SAFIR REGULAR',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE MIXED',
       'RETURNABLE_BOTTLE_LEFFE_LEFFE ROYALE MAPUCHE',
       'RETURNABLE_KEG_SAFIR_SAFIR REGULAR',
       'OW_BOTTLE_CUBANISTO_CUBANISTO PHENOMENAL',
       'OW_BOTTLE_LEFFE_LEFFE RITUEL 9░',
       "OW_BOTTLE_GOOSE ISLAND_ GOOSE ISLAND HONKER'S ALE",
       'OW_BOTTLE_LEFFE_LEFFE BRUNE', 'OW_BOTTLE_LEFFE_LEFFE TRIPLE',
       'OW_BOTTLE_LEFFE_LEFFE ROYALE', 'OW_BOTTLE_LEFFE_LEFFE ROYALE IPA',
       'OW_BOTTLE_KWAK_KWAK',
       'OW_BOTTLE_TRIPEL KARMELIET_TRIPEL KARMELIET',
       'OW_BOTTLE_BIRRA DEL BORGO_BIRRA DEL BORGO CASTAGNALE',
       'RETURNABLE_PERFECTDRAFT_TRIPEL KARMELIET_TRIPEL KARMELIET',
       'RETURNABLE_PERFECTDRAFT_KWAK_KWAK',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE ROYALE CASCADE IPA',
       'RETURNABLE_PERFECTDRAFT_LEFFE_LEFFE RITUEL 9░',
       'OW_BOTTLE_GOOSE ISLAND_GOOS 312',
       'OW_BOTTLE_JUPILER_JUPILER PILS',
       'OW_CAN_BELLE VUE_BELLE VUE KRIEK CLASSIQUE',
       'RETURNABLE_KEG_GINETTE_GINETTE BLANCHE',
       'OW_BOTTLE_LEFFE_LEFFE ROYALE CASCADE IPA',
       'RETURNABLE_KEG_GOOSE ISLAND_GOOSE ISLAND MIDWAY IPA',
       'RETURNABLE_KEG_GINETTE_GINETTE FRUIT',
       'OW_BULK_LEFFE_LEFFE BLONDE',
       'RETURNABLE_KEG_DIEKIRCH_DIEKIRCH GRAND CRU',
       'RETURNABLE_BOTTLE_DIEKIRCH_DIEKIRCH PILS',
       'RETURNABLE_KEG_DIEKIRCH_DIEKIRCH BRUIN',
       'RETURNABLE_PERFECTDRAFT_DIEKIRCH_DIEKIRCH PILS',
       'OW_BULK_PURE BLONDE_PURE BLONDE REGULAR',
       'OW_CAN_LEFFE_LEFFE RUBY', 'OW_BOTTLE_LEFFE_LEFFE',
       'OW_BOTTLE_BELLE VUE_BELLE VUE GUEUZE',
       'OW_BULK_GINETTE_ GINETTE LAGER',
       'RETURNABLE_KEG_GOOSE ISLAND_GOOS 312'))
    Brand = st.selectbox('Please select the brand',('JUPILER', 'PIEDBOEUF', 'DIEKIRCH', 'BELLE VUE', 'HOEGAARDEN',
       'LEFFE', 'TRIPEL KARMELIET', 'GOOSE ISLAND', 'STELLA ARTOIS',
       'CORONA', 'VIEUX TEMPS', 'SCOTCH CTS', 'CUBANISTO', 'GINETTE',
       'KWAK', 'PURE BLONDE', 'BASS', 'KRUGER', "BECK'S", 'HORSE ALE',
       'GINDER-ALE', 'DEUS', 'SAFIR', 'BIRRA DEL BORGO'))
    Sub_brand = st.selectbox('Please select the sub_brand',('JUPILER PILS', 'JUPILER 0,0', 'PIEDBOEUF BLONDE',
       'PIEDBOEUF FONCEE', 'DIEKIRCH PILS', 'BELLE VUE EXTRA KRIEK',
       'HOEGAARDEN ROSEE', 'HOEGAARDEN WHITE', 'FLAVOURED ALCOHOLIC',
       'LEFFE BLONDE', 'TRIPEL KARMELIET', 'GOOSE ISLAND IPA',
       'HOEGAARDEN ROSE 0,0', 'LEFFE BRUNE',
       'LEFFE SANS ALCOOL/ALCOHOLVRIJ', 'BELLE VUE GUEUZE', 'LEFFE RUBY',
       'STELLA ARTOIS REGULAR', 'BELLE VUE KRIEK CLASSIQUE',
       'CORONA EXTRA', 'JUPILER BLUE', 'VIEUX TEMPS REGULAR',
       'SCOTCH CTS', 'HOEG RADLER LEMON 0,0', 'CUBANISTO RUM',
       ' GINETTE LAGER', 'GINETTE FRUIT', 'GINETTE TRIPEL', 'KWAK',
       'HOEGAARDEN JULIUS', 'LEFFE', 'LEFFE ROYALE', 'LEFFE TRIPLE',
       'HOEGAARDEN BEATRIX', 'HOEGAARDEN YELLOW', 'PURE BLONDE REGULAR',
       'BASS PALE ALE', 'KRUGER EXPORT', 'HOEGAARDEN 0,0',
       'LEFFE RITUEL 9░', 'HOEGAARDEN GRAND CRU',
       'LEFFE ROYALE CASCADE IPA', 'GINETTE BLONDE',
       'HOEGAARDEN FORBIDDEN FRUIT', ' HOEGAARDEN RADLER AGRUM 0,0',
       "BECK'S REGULAR", 'HORSE ALE', 'LEFFE RADIEUSE',
       'PIEDBOEUF TRIPLE', 'GINETTE BLANCHE', 'DIEKIRCH XMAS BEER',
       'GINDER-ALE', 'LEFF NECT', 'DIEKIRCH GRAND CRU', 'DEUS',
       'SAFIR REGULAR', 'LEFFE MIXED', 'CUBANISTO PHENOMENAL',
       " GOOSE ISLAND HONKER'S ALE", 'LEFFE ROYALE IPA',
       'BIRRA DEL BORGO CASTAGNALE', 'GOOS 312',
       'GOOSE ISLAND MIDWAY IPA', 'DIEKIRCH BRUIN',
       'LEFFE ROYALE MAPUCHE'))
    pack_type = st.selectbox('Please select the pack type',('BOTTLE', 'BULK', 'KEG', 'CAN', 'PERFECTDRAFT'))
    returnable = st.selectbox('Please select the returnability type',('RETURNABLE', 'OW'))
    GTO_2019 = st.number_input('Please enter the GTO 2019',format='%f',value=float())
    Volume_2019_Product = st.number_input('Please enter the Volume 2019 Product',format='%f',value=float())
    Tax = st.number_input('Please enter the tax to be levied',format='%f',value=float())
    province = st.selectbox('Please select the province',('Brussels Capital Region', 'Antwerp', 'Namur', 'Liège', 'Limburg',
       'Hainaut', 'East Flanders', 'Flemish Brabant', 'West Flanders',
       'Luxembourg', 'Walloon Brabant'))
    
    data = {'Ship-to ID': Ship_to_ID, 'Volume_2019': Volume_2019, 'Volume_2018': Volume_2018, 'sfdc_tier': sfdc_tier, 
            'poc_image': poc_image, 'segment': segment, 'sub_segment': sub_segment, 'Product Set': Product_Set, 'Brand': Brand, 
            'Sub-Brand': Sub_brand, 'Pack_Type': pack_type, 'Returnalility': returnable, 'GTO_2019': GTO_2019, 
            'Volume_2019 Product': Volume_2019_Product, 'Tax': Tax, 'province':province}
    features = pd.DataFrame(data, index=[0])
    return features

from predict import predict_disc

dfus = user_input_features()
st.header('User Input')
st.write(dfus.T)
off_pred,on_pred,Discount_pred,Discount_perc = [0,0,0,0]
if abs(dfus['GTO_2019'][0])>0.001 and abs(dfus['Volume_2019 Product'][0])>0.001 and ((dfus['GTO_2019'][0] - dfus['Tax'][0])*dfus['Volume_2019 Product'][0]>=0) and ((dfus['GTO_2019'][0] - dfus['Tax'][0])*dfus['Tax'][0]>=0):
   off_pred,on_pred,Discount_pred,Discount_perc = predict_disc(dfus)
st.subheader('Offinvoice Discount : %f'%off_pred)
st.subheader('Oninvoice Discount : %f'%on_pred)
st.subheader('Total Discount : %f'%Discount_pred)